# ce fichier decrit les services, il va etre consomme par la commande :
# docker-compose up -d
# cette commande va creer l'image et la lancer
# ensuite pour verifier que ca tourne:
# docker ps
# pour tester :
# curl http://localhost:8081
# ... ou bien un equivalent dans un navigateur web
# pour arreter
# docker stop cat-php-apache
version: '3.8'

services:
  php-apache-environment:
    # ce nom doit etre unique sur votre serveur, penser a le personnaliser si vous dupliquez le projet
    container_name: cat-php-apache
    build:
        context: ./
        dockerfile: Dockerfile
    # liste des espaces disques sous le format "chemin-local:chemin-interne-container"
    volumes:
      - ./src/:/var/www/html/
    # liste des ports sous le format "port-local:port-interne-container"
    ports:
      - 8081:80
